### ISSUE TITLE
contribute with code material, building a open-source achieve to learn coding

### ISSUE THREAD

**Issue by stefanmiodrag** [stefanmiodrag/coderbits#1]
Hey,

Felt that due to #hacktoberfest, I wanted to create a repository where people could contribute. Looking for tutorials, tips, etc. For example "introduction to git" or "learn sass", etc.

Simply fork this repository and create a new .md file. You don't necessarily need to type everything about the subject since people could later expand / contribute to your text. At the moment, this is just an experiment, but could potentially be turned into a site.

If you have any questions, let me know! 👍

**Comment by Gvilgorin** [comment]
Hello, 
I was wondering if Java would be a good place for some basic tutorials, or tips? Also, did you want any code written or just some text file with an explanation of the tutorial or tip?

**Comment by stefanmiodrag** [comment]
Hey @Gvilgorin, definitely! I'd like for it to cover as many languages as possible! Depending on the time you're willing to spend. If you want to contribute something smaller, like a short tutorial, that's fine. If you want an overall introduction to java, that's fine as well 😄 👍 

Right now I'm just looking for as many contributions as possible, once we have a decent amount. We'd create a directory structure for it.
